// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: spotify_curate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type General struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success        bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FailureDetails string `protobuf:"bytes,2,opt,name=failure_details,json=failureDetails,proto3" json:"failure_details,omitempty"`
}

func (x *General) Reset() {
	*x = General{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *General) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*General) ProtoMessage() {}

func (x *General) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use General.ProtoReflect.Descriptor instead.
func (*General) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{0}
}

func (x *General) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *General) GetFailureDetails() string {
	if x != nil {
		return x.FailureDetails
	}
	return ""
}

type AuthenticateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{1}
}

type AuthenticateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSpotifyId string   `protobuf:"bytes,1,opt,name=user_spotify_id,json=userSpotifyId,proto3" json:"user_spotify_id,omitempty"`
	General       *General `protobuf:"bytes,2,opt,name=general,proto3" json:"general,omitempty"`
}

func (x *AuthenticateUserResponse) Reset() {
	*x = AuthenticateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserResponse) ProtoMessage() {}

func (x *AuthenticateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateUserResponse) GetUserSpotifyId() string {
	if x != nil {
		return x.UserSpotifyId
	}
	return ""
}

func (x *AuthenticateUserResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

type UpdateUserDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUserDataRequest) Reset() {
	*x = UpdateUserDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataRequest) ProtoMessage() {}

func (x *UpdateUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserDataRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{3}
}

type UpdateUserDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *General `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
}

func (x *UpdateUserDataResponse) Reset() {
	*x = UpdateUserDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataResponse) ProtoMessage() {}

func (x *UpdateUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserDataResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserDataResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

type CreatePlaylistRecentInGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre []string `protobuf:"bytes,1,rep,name=genre,proto3" json:"genre,omitempty"`
}

func (x *CreatePlaylistRecentInGenreRequest) Reset() {
	*x = CreatePlaylistRecentInGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaylistRecentInGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRecentInGenreRequest) ProtoMessage() {}

func (x *CreatePlaylistRecentInGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRecentInGenreRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRecentInGenreRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePlaylistRecentInGenreRequest) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

type CreatePlaylistRecentInGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *General `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
}

func (x *CreatePlaylistRecentInGenreResponse) Reset() {
	*x = CreatePlaylistRecentInGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaylistRecentInGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRecentInGenreResponse) ProtoMessage() {}

func (x *CreatePlaylistRecentInGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRecentInGenreResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRecentInGenreResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePlaylistRecentInGenreResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

type CreatePlaylistRecentInGenreAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePlaylistRecentInGenreAllRequest) Reset() {
	*x = CreatePlaylistRecentInGenreAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaylistRecentInGenreAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRecentInGenreAllRequest) ProtoMessage() {}

func (x *CreatePlaylistRecentInGenreAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRecentInGenreAllRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRecentInGenreAllRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{7}
}

type CreatePlaylistRecentInGenreAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *General `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
}

func (x *CreatePlaylistRecentInGenreAllResponse) Reset() {
	*x = CreatePlaylistRecentInGenreAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaylistRecentInGenreAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRecentInGenreAllResponse) ProtoMessage() {}

func (x *CreatePlaylistRecentInGenreAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRecentInGenreAllResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRecentInGenreAllResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePlaylistRecentInGenreAllResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

type GetUnmappedArtistsForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSpotifyId string `protobuf:"bytes,1,opt,name=user_spotify_id,json=userSpotifyId,proto3" json:"user_spotify_id,omitempty"`
}

func (x *GetUnmappedArtistsForUserRequest) Reset() {
	*x = GetUnmappedArtistsForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnmappedArtistsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnmappedArtistsForUserRequest) ProtoMessage() {}

func (x *GetUnmappedArtistsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnmappedArtistsForUserRequest.ProtoReflect.Descriptor instead.
func (*GetUnmappedArtistsForUserRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnmappedArtistsForUserRequest) GetUserSpotifyId() string {
	if x != nil {
		return x.UserSpotifyId
	}
	return ""
}

type GetUnmappedArtistsForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *General  `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	Artists []*Artist `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists,omitempty"`
}

func (x *GetUnmappedArtistsForUserResponse) Reset() {
	*x = GetUnmappedArtistsForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnmappedArtistsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnmappedArtistsForUserResponse) ProtoMessage() {}

func (x *GetUnmappedArtistsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnmappedArtistsForUserResponse.ProtoReflect.Descriptor instead.
func (*GetUnmappedArtistsForUserResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnmappedArtistsForUserResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *GetUnmappedArtistsForUserResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uri       string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{11}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateGenreToArtistsMappingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSpotifyId          string                   `protobuf:"bytes,1,opt,name=user_spotify_id,json=userSpotifyId,proto3" json:"user_spotify_id,omitempty"`
	GenreToArtistsMappings []*GenreToArtistsMapping `protobuf:"bytes,2,rep,name=genre_to_artists_mappings,json=genreToArtistsMappings,proto3" json:"genre_to_artists_mappings,omitempty"`
}

func (x *CreateGenreToArtistsMappingsRequest) Reset() {
	*x = CreateGenreToArtistsMappingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreToArtistsMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreToArtistsMappingsRequest) ProtoMessage() {}

func (x *CreateGenreToArtistsMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreToArtistsMappingsRequest.ProtoReflect.Descriptor instead.
func (*CreateGenreToArtistsMappingsRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGenreToArtistsMappingsRequest) GetUserSpotifyId() string {
	if x != nil {
		return x.UserSpotifyId
	}
	return ""
}

func (x *CreateGenreToArtistsMappingsRequest) GetGenreToArtistsMappings() []*GenreToArtistsMapping {
	if x != nil {
		return x.GenreToArtistsMappings
	}
	return nil
}

type GenreToArtistsMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre       string   `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	ArtistNames []string `protobuf:"bytes,2,rep,name=artist_names,json=artistNames,proto3" json:"artist_names,omitempty"`
}

func (x *GenreToArtistsMapping) Reset() {
	*x = GenreToArtistsMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenreToArtistsMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreToArtistsMapping) ProtoMessage() {}

func (x *GenreToArtistsMapping) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreToArtistsMapping.ProtoReflect.Descriptor instead.
func (*GenreToArtistsMapping) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{13}
}

func (x *GenreToArtistsMapping) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *GenreToArtistsMapping) GetArtistNames() []string {
	if x != nil {
		return x.ArtistNames
	}
	return nil
}

type CreateGenreToArtistsMappingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General                      *General                 `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	FailedGenreToArtistsMappings []*GenreToArtistsMapping `protobuf:"bytes,2,rep,name=failed_genre_to_artists_mappings,json=failedGenreToArtistsMappings,proto3" json:"failed_genre_to_artists_mappings,omitempty"`
}

func (x *CreateGenreToArtistsMappingsResponse) Reset() {
	*x = CreateGenreToArtistsMappingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreToArtistsMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreToArtistsMappingsResponse) ProtoMessage() {}

func (x *CreateGenreToArtistsMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreToArtistsMappingsResponse.ProtoReflect.Descriptor instead.
func (*CreateGenreToArtistsMappingsResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGenreToArtistsMappingsResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *CreateGenreToArtistsMappingsResponse) GetFailedGenreToArtistsMappings() []*GenreToArtistsMapping {
	if x != nil {
		return x.FailedGenreToArtistsMappings
	}
	return nil
}

type CreateLabelsForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSpotifyId string   `protobuf:"bytes,1,opt,name=user_spotify_id,json=userSpotifyId,proto3" json:"user_spotify_id,omitempty"`
	Labels        []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *CreateLabelsForUserRequest) Reset() {
	*x = CreateLabelsForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLabelsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelsForUserRequest) ProtoMessage() {}

func (x *CreateLabelsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelsForUserRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelsForUserRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{15}
}

func (x *CreateLabelsForUserRequest) GetUserSpotifyId() string {
	if x != nil {
		return x.UserSpotifyId
	}
	return ""
}

func (x *CreateLabelsForUserRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateLabelsForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General      *General `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	FailedLabels []string `protobuf:"bytes,2,rep,name=failed_labels,json=failedLabels,proto3" json:"failed_labels,omitempty"`
}

func (x *CreateLabelsForUserResponse) Reset() {
	*x = CreateLabelsForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLabelsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelsForUserResponse) ProtoMessage() {}

func (x *CreateLabelsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelsForUserResponse.ProtoReflect.Descriptor instead.
func (*CreateLabelsForUserResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{16}
}

func (x *CreateLabelsForUserResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *CreateLabelsForUserResponse) GetFailedLabels() []string {
	if x != nil {
		return x.FailedLabels
	}
	return nil
}

type GetArtistTagsForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSpotifyId string `protobuf:"bytes,1,opt,name=user_spotify_id,json=userSpotifyId,proto3" json:"user_spotify_id,omitempty"`
}

func (x *GetArtistTagsForUserRequest) Reset() {
	*x = GetArtistTagsForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistTagsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistTagsForUserRequest) ProtoMessage() {}

func (x *GetArtistTagsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistTagsForUserRequest.ProtoReflect.Descriptor instead.
func (*GetArtistTagsForUserRequest) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{17}
}

func (x *GetArtistTagsForUserRequest) GetUserSpotifyId() string {
	if x != nil {
		return x.UserSpotifyId
	}
	return ""
}

type GetArtistTagsForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *General `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *GetArtistTagsForUserResponse) Reset() {
	*x = GetArtistTagsForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_curate_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistTagsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistTagsForUserResponse) ProtoMessage() {}

func (x *GetArtistTagsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_curate_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistTagsForUserResponse.ProtoReflect.Descriptor instead.
func (*GetArtistTagsForUserResponse) Descriptor() ([]byte, []int) {
	return file_spotify_curate_proto_rawDescGZIP(), []int{18}
}

func (x *GetArtistTagsForUserResponse) GetGeneral() *General {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *GetArtistTagsForUserResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_spotify_curate_proto protoreflect.FileDescriptor

var file_spotify_curate_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c,
	0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x19, 0x0a, 0x17,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x18, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x22, 0x3a, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x22, 0x4f,
	0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x22,
	0x27, 0x0a, 0x25, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x26, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x20,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x46, 0x6f,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x07,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x22, 0x79, 0x0a, 0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x23,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x57, 0x0a, 0x19, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x5f,
	0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x16, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x50, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x24, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c,
	0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x64, 0x0a, 0x20, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x52, 0x1c, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x5c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x46,
	0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x6c, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x46, 0x6f, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x07, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x45, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x46, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x49, 0x64, 0x22, 0x5c, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54,
	0x61, 0x67, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x32, 0xe0, 0x06, 0x0a, 0x0d, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x75, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x7f, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x41, 0x6c, 0x6c, 0x12, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x70, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x6d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x6f, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x46,
	0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67,
	0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x46, 0x6f,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x67, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x72, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x2f, 0x73, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spotify_curate_proto_rawDescOnce sync.Once
	file_spotify_curate_proto_rawDescData = file_spotify_curate_proto_rawDesc
)

func file_spotify_curate_proto_rawDescGZIP() []byte {
	file_spotify_curate_proto_rawDescOnce.Do(func() {
		file_spotify_curate_proto_rawDescData = protoimpl.X.CompressGZIP(file_spotify_curate_proto_rawDescData)
	})
	return file_spotify_curate_proto_rawDescData
}

var file_spotify_curate_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_spotify_curate_proto_goTypes = []interface{}{
	(*General)(nil),                                // 0: proto.General
	(*AuthenticateUserRequest)(nil),                // 1: proto.AuthenticateUserRequest
	(*AuthenticateUserResponse)(nil),               // 2: proto.AuthenticateUserResponse
	(*UpdateUserDataRequest)(nil),                  // 3: proto.UpdateUserDataRequest
	(*UpdateUserDataResponse)(nil),                 // 4: proto.UpdateUserDataResponse
	(*CreatePlaylistRecentInGenreRequest)(nil),     // 5: proto.CreatePlaylistRecentInGenreRequest
	(*CreatePlaylistRecentInGenreResponse)(nil),    // 6: proto.CreatePlaylistRecentInGenreResponse
	(*CreatePlaylistRecentInGenreAllRequest)(nil),  // 7: proto.CreatePlaylistRecentInGenreAllRequest
	(*CreatePlaylistRecentInGenreAllResponse)(nil), // 8: proto.CreatePlaylistRecentInGenreAllResponse
	(*GetUnmappedArtistsForUserRequest)(nil),       // 9: proto.GetUnmappedArtistsForUserRequest
	(*GetUnmappedArtistsForUserResponse)(nil),      // 10: proto.GetUnmappedArtistsForUserResponse
	(*Artist)(nil),                                 // 11: proto.Artist
	(*CreateGenreToArtistsMappingsRequest)(nil),    // 12: proto.CreateGenreToArtistsMappingsRequest
	(*GenreToArtistsMapping)(nil),                  // 13: proto.GenreToArtistsMapping
	(*CreateGenreToArtistsMappingsResponse)(nil),   // 14: proto.CreateGenreToArtistsMappingsResponse
	(*CreateLabelsForUserRequest)(nil),             // 15: proto.CreateLabelsForUserRequest
	(*CreateLabelsForUserResponse)(nil),            // 16: proto.CreateLabelsForUserResponse
	(*GetArtistTagsForUserRequest)(nil),            // 17: proto.GetArtistTagsForUserRequest
	(*GetArtistTagsForUserResponse)(nil),           // 18: proto.GetArtistTagsForUserResponse
	(*timestamppb.Timestamp)(nil),                  // 19: google.protobuf.Timestamp
}
var file_spotify_curate_proto_depIdxs = []int32{
	0,  // 0: proto.AuthenticateUserResponse.general:type_name -> proto.General
	0,  // 1: proto.UpdateUserDataResponse.general:type_name -> proto.General
	0,  // 2: proto.CreatePlaylistRecentInGenreResponse.general:type_name -> proto.General
	0,  // 3: proto.CreatePlaylistRecentInGenreAllResponse.general:type_name -> proto.General
	0,  // 4: proto.GetUnmappedArtistsForUserResponse.general:type_name -> proto.General
	11, // 5: proto.GetUnmappedArtistsForUserResponse.artists:type_name -> proto.Artist
	19, // 6: proto.Artist.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: proto.CreateGenreToArtistsMappingsRequest.genre_to_artists_mappings:type_name -> proto.GenreToArtistsMapping
	0,  // 8: proto.CreateGenreToArtistsMappingsResponse.general:type_name -> proto.General
	13, // 9: proto.CreateGenreToArtistsMappingsResponse.failed_genre_to_artists_mappings:type_name -> proto.GenreToArtistsMapping
	0,  // 10: proto.CreateLabelsForUserResponse.general:type_name -> proto.General
	0,  // 11: proto.GetArtistTagsForUserResponse.general:type_name -> proto.General
	1,  // 12: proto.SpotifyCurate.AuthenticateUser:input_type -> proto.AuthenticateUserRequest
	3,  // 13: proto.SpotifyCurate.UpdateUserData:input_type -> proto.UpdateUserDataRequest
	5,  // 14: proto.SpotifyCurate.CreatePlaylistRecentInGenre:input_type -> proto.CreatePlaylistRecentInGenreRequest
	7,  // 15: proto.SpotifyCurate.CreatePlaylistRecentInGenreAll:input_type -> proto.CreatePlaylistRecentInGenreAllRequest
	9,  // 16: proto.SpotifyCurate.GetUnmappedArtistsForUser:input_type -> proto.GetUnmappedArtistsForUserRequest
	12, // 17: proto.SpotifyCurate.CreateGenreToArtistsMappings:input_type -> proto.CreateGenreToArtistsMappingsRequest
	15, // 18: proto.SpotifyCurate.CreateLabelsForUser:input_type -> proto.CreateLabelsForUserRequest
	17, // 19: proto.SpotifyCurate.GetArtistTagsForUser:input_type -> proto.GetArtistTagsForUserRequest
	2,  // 20: proto.SpotifyCurate.AuthenticateUser:output_type -> proto.AuthenticateUserResponse
	4,  // 21: proto.SpotifyCurate.UpdateUserData:output_type -> proto.UpdateUserDataResponse
	6,  // 22: proto.SpotifyCurate.CreatePlaylistRecentInGenre:output_type -> proto.CreatePlaylistRecentInGenreResponse
	8,  // 23: proto.SpotifyCurate.CreatePlaylistRecentInGenreAll:output_type -> proto.CreatePlaylistRecentInGenreAllResponse
	10, // 24: proto.SpotifyCurate.GetUnmappedArtistsForUser:output_type -> proto.GetUnmappedArtistsForUserResponse
	14, // 25: proto.SpotifyCurate.CreateGenreToArtistsMappings:output_type -> proto.CreateGenreToArtistsMappingsResponse
	16, // 26: proto.SpotifyCurate.CreateLabelsForUser:output_type -> proto.CreateLabelsForUserResponse
	18, // 27: proto.SpotifyCurate.GetArtistTagsForUser:output_type -> proto.GetArtistTagsForUserResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_spotify_curate_proto_init() }
func file_spotify_curate_proto_init() {
	if File_spotify_curate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spotify_curate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*General); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaylistRecentInGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaylistRecentInGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaylistRecentInGenreAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaylistRecentInGenreAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnmappedArtistsForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnmappedArtistsForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGenreToArtistsMappingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenreToArtistsMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGenreToArtistsMappingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLabelsForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLabelsForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtistTagsForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_curate_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtistTagsForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spotify_curate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spotify_curate_proto_goTypes,
		DependencyIndexes: file_spotify_curate_proto_depIdxs,
		MessageInfos:      file_spotify_curate_proto_msgTypes,
	}.Build()
	File_spotify_curate_proto = out.File
	file_spotify_curate_proto_rawDesc = nil
	file_spotify_curate_proto_goTypes = nil
	file_spotify_curate_proto_depIdxs = nil
}
