version: '3.8'

services:
  spotify_db:
    image: postgres:latest
    container_name: spotify_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - spotify-app-postgres-data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./changelog:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    command: liquibase --changeLogFile=changelogs/master.yml --url=jdbc:postgresql://localhost:5432/postgres --username=root --password=root update
    depends_on:
      - spotify_db

volumes:
  spotify-app-postgres-data: